### ISSUE TITLE
Refactor the code to use javascript best practices

### ISSUE THREAD

**Issue by ruta-goomba** [aguillaume/TicTacToe#12]
Use the best Javascript practices as described in 'Javascript: the Good Parts'(http://www.amazon.co.uk/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742)

**Comment by aguillaume** [comment]
I need to read the whole book??

**Comment by ruta-goomba** [comment]
I’ll send you some links to most relevant articles ☺ However, the book is rather small, easily read in couple of evenings.

**Comment by ruta-goomba** [comment]
Javascript Function Invocation Patterns:
http://doctrina.org/Javascript-Function-Invocation-Patterns.html

Javascript scope and closures:
http://doctrina.org/JavaScript:Why-Understanding-Scope-And-Closures-Matter.html#closures

Javascript object prototypes:
http://doctrina.org/Javascript-Objects-Prototypes.html#pcip

Some others to follow later…

**Comment by aguillaume** [comment]
If it is such a short book then I'll have a look at it. I'll check out the articles as well. Thanks for those :) :+1:

**Comment by aguillaume** [comment]
I've been reading the articles you provided, and they are very intense... also some what confusing. I will have to re-read them a few times when I try to put them into practice. 

I have been trying to design a Board object that can be used through out the Tic Tact Toe. 

Are there any particular examples of bad coding in the Tic Tac Toe that you have seen? @ruta-goomba

**Comment by ruta-goomba** [comment]
Hi Guillaume,

TicTacToe is a small project not intended to expand massively so the code we have there is perfectly fine for that purpose. However, I’m taking this as a learning experience as well as a little project and I think we both want to learn the best practices that could later be used for larger scale projects. If we look at it from such perspective, then there are a few things we could do (sorry I didn’t have a chance to start on that):

1)      Use only local scope variables, stop using global scope variables

2)      Replace function declarations with function expressions

3)      Avoid initiating functions with new keyword

4)      Replace all i++ with i+= 1

5)      Implement memoization for recursive function I introduced

Can’t think of anything else at the moment. If you want, we can have a meeting to discuss all this. Let me know.

Ruta

**Comment by aguillaume** [comment]
yes defiantly a learning experience. I  have only started going through the book, and read the articles.. but i need to re - read them because i am still struggling to understand the whole function stuff...
